import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// Get current directory in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const htmlContent = fs.readFileSync(
  path.join(__dirname, "../typescript/package/paywall-app/dist/index.html"),
  "utf8"
);
const moduleDir = path.join(
  __dirname,
  "../typescript/package/src/shared/paywall"
);
const moduleFile = path.join(moduleDir, "paywallHtml.ts");

// Ensure directory exists
fs.mkdirSync(moduleDir, { recursive: true });

// Create JS module with properly escaped content
// so that it can be imported as a module
const tsContent = `// This file is generated by build-paywall.js
export const paywallHtml = ${JSON.stringify(htmlContent)};
`;

fs.writeFileSync(moduleFile, tsContent);

console.log("Created JavaScript module at", moduleFile);
